# Generated by Django 3.2.8 on 2021-11-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20211101_1251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regi',
            table='regi',
        ),
        migrations.AlterModelTable(
            name='user',
            table='test_user',
        ),
    ]
