# Generated by Django 3.2.8 on 2021-11-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20211101_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regi',
        ),
    ]
