# Generated by Django 3.2.7 on 2021-09-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_auto_20210927_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Furits',
        ),
    ]
